version: '3'
services:

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    restart: unless-stopped
    volumes:
      - /certbot/conf:/etc/letsencrypt
      - /certbot/conf:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  nginx:
    container_name: my-nginx
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - certbot
    volumes:    
      - /certbot/conf:/etc/letsencrypt
      - /certbot/conf:/var/www/certbot
    restart: on-failure
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  naraapi:
    container_name: my-naraapi
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - /certbot/conf:/etc/letsencrypt
      - /certbot/conf:/var/www/certbot
    depends_on:
      - certbot
      - nginx
    restart: on-failure
